name: Build wget2 for Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install meson ninja
      - name: Build dependencies
        run: bash build_deps.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: prebuilt-dependencies
          path: dependencies/

  build-wget2:
    runs-on: ubuntu-latest
    needs: build-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: prebuilt-dependencies
          path: dependencies/
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install meson ninja
      - name: Configure Meson
        run: meson setup build --buildtype=release
      - name: Build with Ninja
        run: ninja -C build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wget2-build
          path: build/wget2.exe
